use_gpu: true

run:
    output_dir: predictions
    predict_on_data_partition: test

defaults:
    - data: dataBreakdown

system:
    load: /content/video_guided_machine_translation/Model Vatex 1/model-04_1.104.hdf5

    batch_size: 64
    num_data_workers: 0

    model:
        outputs:
            word_level:
                target: false
                gaps: false
                source: false
            sentence_level:
                hter: true